Fix: Suppression du controle de surface sur les propriétés requises - close #334 & #417
voyages-sncf-technologies/hesperides-gui pull request #419
Opened 2020-10-28 14:24 UTC by Lucas-C

The following backend error message is still displayed:
![2020-10-28 15_22_19-Hesperides _ Properties](https://user-images.githubusercontent.com/925560/97449154-ace96180-1931-11eb-92c2-5b552453de0d.png)

2020-10-28 14:26 UTC, thomaslhostis approved these changes
👍

2020-10-28 16:04 UTC, thomaslhostis requested changes

2020-10-28 16:04 UTC, thomaslhostis commented on test/bdd/features/platforms/save-module-properties.feature
> +    Then the save button is enabled
👍 👍

2020-10-28 16:04 UTC, thomaslhostis commented on test/bdd/glue/scenarios/platforms/module-properties-list.js
> +            await expect(childSpan.getAttribute('class')).to.eventually.equal('property-required');
Peux-tu extraire ceci dans `assert.js` ? :)

2020-10-28 16:11 UTC, Lucas-C commented on .travis/run_bdd_test.sh
> +cd $(dirname ${BASH_SOURCE[0]})
C'est le mode "strict" de Bash :
- http://redsymbol.net/articles/unofficial-bash-strict-mode/
- https://kvz.io/bash-best-practices.html

2020-10-28 16:12 UTC, Lucas-C commented on test/bdd/glue/scenarios/platforms/module-properties-list.js
> +            await expect(childSpan.getAttribute('class')).to.eventually.equal('property-required');
J'ai pas très envie, comme ce code n'est utilisé nul part ailleurs et ne me semble pas très réutilisable...
Après si tu as des arguments je veux bien être convaincu :)

2020-10-28 16:16 UTC, thomaslhostis commented on test/bdd/glue/scenarios/platforms/module-properties-list.js
> +            await expect(childSpan.getAttribute('class')).to.eventually.equal('property-required');
(J'ai failli répondre "flemme" ^^')

C'est pour l'homogénéité. Tous les `expect` sont faits dans `assert.js`. Quitte à rendre cette assertion un peu plus générique. Qu'en penses-tu ?

2020-10-28 20:43 UTC, Lucas-C commented on test/bdd/glue/scenarios/platforms/module-properties-list.js
> +            await expect(childSpan.getAttribute('class')).to.eventually.equal('property-required');
C'est fait. Par contre à bien regarder `assert.js` je pense qu'il y a pas mal de fonctions qui n'ont aucun intérêt à être `async`... Si c'est pour les invoquer avec `await` à chaque fois, ça n'a pas grand intérêt ^^

2020-10-28 20:52 UTC, merged

2020-10-29 07:31 UTC, thomaslhostis commented on test/bdd/glue/scenarios/platforms/module-properties-list.js
> +            await expect(childSpan.getAttribute('class')).to.eventually.equal('property-required');
Comme quoi ?

2020-10-29 07:35 UTC, thomaslhostis commented on test/bdd/glue/scenarios/platforms/module-properties-list.js
> +            await expect(childSpan.getAttribute('class')).to.eventually.equal('property-required');
<img width="689" alt="Capture d’écran 2020-10-29 à 08 34 46" src="https://user-images.githubusercontent.com/4296630/97539070-adc9d400-19c1-11eb-9ead-93c6bb34983b.png">

2020-10-29 07:38 UTC, thomaslhostis commented on test/bdd/glue/scenarios/platforms/module-properties-list.js
> +            await expect(childSpan.getAttribute('class')).to.eventually.equal('property-required');
Le linter ne passe pas à cause de ça :)

2020-10-29 07:42 UTC, thomaslhostis commented on test/bdd/glue/scenarios/platforms/module-properties-list.js
> +            await expect(childSpan.getAttribute('class')).to.eventually.equal('property-required');
De plus je te propose d'utiliser la méthode existante`isPresentByCss` qui fait la même chose il me semble :)

2020-10-29 07:47 UTC, thomaslhostis commented on test/bdd/glue/scenarios/platforms/module-properties-list.js
> +            await expect(childSpan.getAttribute('class')).to.eventually.equal('property-required');
Pas que le linter : https://travis-ci.com/github/voyages-sncf-technologies/hesperides-gui/builds/195079066

^^